apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-webhook-dingtalk
  namespace: monitoring
  labels:
    app: prometheus-webhook-dingtalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-webhook-dingtalk
  template:
    metadata:
      labels:
        app: prometheus-webhook-dingtalk
    spec:
      containers:
      - name: prometheus-webhook-dingtalk
        image: timonwong/prometheus-webhook-dingtalk:latest
        ports:
        - containerPort: 8060
        env:
        - name: DINGTALK_WEBHOOK
          value: "https://oapi.dingtalk.com/robot/send?access_token=5dd69c794990ec190df2b71bcaa0e00bc0bdb411918639c5baa68f3d982a843d"
        - name: DINGTALK_SECRET
          value: "SEC1763f0d71c7be760a53bd5e1148a1da72e35e483bdedf75b05e39e8c6f3af42d"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus-webhook
      volumes:
      - name: config-volume
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-webhook-dingtalk
  namespace: monitoring
spec:
  ports:
  - port: 8060
    targetPort: 8060
  selector:
    app: prometheus-webhook-dingtalk
  type: ClusterIP
